### ISSUE TITLE
Issue with multi-class active learning

### ISSUE THREAD

**Issue by tjbrailey** [activetext/activeText#5]
Hi again, 

Quick question on using active learning with more than two categories. Here is the set up - I am taking your example and adding a hypothetical third class "Unsure".

```
results <- 
  activeText::active_label(
  docs = activeText::bbc_data_all,
  n_class = 3,
  seed = 1,
  labels = c("Not Political", "Political", "Unsure"))
```

First, I assume that you need to set n_class to be the number of distinct categories you are looking to classify articles into. When I do this however, after the first round of manual labelling, I get the error:

```
Error in keywords_list[[i]] : subscript out of bounds
```

Are keywords necessary for >2 labels? Also, if I set `n_class` to the default, this doesn't give me the predictions for the third class "Unsure", as expected, though the code runs to completion.

I think I might be misunderstanding something in the way activeText works for more than two categories - any advice would be much appreciated! Also, I realise that the paper hasn't been published just yet, so if you would like me to hold off on creating issue tickets for the time being, just let me know! 

Session info as before: 

```
R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22631)

Matrix products: default


locale:
[1] LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=English_United Kingdom.utf8    LC_MONETARY=English_United Kingdom.utf8
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.utf8    

time zone: Europe/London
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RSQLite_2.3.6

loaded via a namespace (and not attached):
 [1] bit_4.0.5         compiler_4.3.2    fastmap_1.1.1     cli_3.6.2         DBI_1.2.2         tools_4.3.2       rstudioapi_0.16.0
 [8] memoise_2.0.1     bit64_4.0.5       vctrs_0.6.5       cachem_1.0.8      blob_1.2.4        rlang_1.1.3      
```

**Comment by vrhopkins** [comment]
+1 I had this same question!

**Comment by mbosley** [comment]
thanks for this comment! I think you're running into some issues where the logic for the keyword feature isn't playing nicely with the multi-class classification. We'll work on getting a fix for this out soon. Thanks for bringing it to our attention!

**Comment by esallenback** [comment]
Thanks again for creating the issue, it should be fixed now! By the way, the most recent merge has removed the "n_class" parameter since this is redundant as it can be extracted from the length of "labels."
