### ISSUE TITLE
Multiclass labels output

### ISSUE THREAD

**Issue by vrhopkins** [activetext/activeText#7]
Hello,

I'm having an issue generating probability estimates for multiclass labeling. 

After updating the package and running the multiclass example as:

```
results <-
  activeText::active_label(
    docs = activeText::bbc_data_all,
    seed = 1,
    labels = c("Not Political", "Political", "Unsure"))
```
As expected, the console states:

```
"NOTE: The number of classes has been set to  3  based on `labels.`"
```
So far so good. 

But once the model finishes after labeling, the output only lists two probability vectors (“Class_1” and “Class_2”). Is this expected or am I doing something wrong?

![image](https://github.com/activetext/activeText/assets/92007259/3d5e0407-d88d-484a-a149-03e918d8ec36)

Thank you!
 
**R Session Info**
```
R version 4.4.0 (2024-04-24)
Platform: aarch64-apple-darwin20
Running under: macOS Ventura 13.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Vancouver
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.4.0    tools_4.4.0       rstudioapi_0.16.0
```

**Comment by ksaki** [comment]
Hello, Thank you for creating this issue! We have fixed this issue with the most recent update by this commit: 7afb581407cebd10a9a305fa06eb3f8a38d80a01.
